package serverProgram;

public enum STATE {
    SET_PLAYERNAME,
    READY_TO_PLAY,
    ASK_CATEGORY,
    SET_CATEGORY,
    SEND_QUESTION,
    HANDLE_ANSWER,
    SEND_QUESTIONLIST,
    CHANGE_SCENE,
    GAME_OVER
}
